"""
YieldLens Constants
Central location for all constant values used across the application.
"""

CREDIT_RATINGS: list[str] = [
    "AAA",
    "AA+",
    "AA",
    "AA-",
    "A+",
    "A",
    "A-",
    "BBB+",
    "BBB",
    "BBB-",
    "BB+",
    "BB",
    "BB-",
    "B+",
    "B",
    "B-",
    "CCC+",
    "CCC",
    "CCC-",
    "CC",
    "C",
    "D",
]

BOND_TYPES: list[str] = [
    "treasury",
    "corporate",
    "municipal",
    "tips",
    "bond_etf",
    "high_yield",
    "preferred",
    "cd",
    "money_market",
]

SECTORS: list[str] = [
    "Technology",
    "Financial Services",
    "Healthcare",
    "Energy",
    "Consumer Discretionary",
    "Consumer Staples",
    "Industrials",
    "Materials",
    "Utilities",
    "Real Estate",
    "Communications",
    "Government",
    "Municipal",
]

US_STATES: list[str] = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
]

TREASURY_MATURITIES: list[str] = [
    "1 Mo",
    "2 Mo",
    "3 Mo",
    "4 Mo",
    "6 Mo",
    "1 Yr",
    "2 Yr",
    "3 Yr",
    "5 Yr",
    "7 Yr",
    "10 Yr",
    "20 Yr",
    "30 Yr",
]

# FRED series IDs for Treasury yields
TREASURY_SERIES: dict[str, str] = {
    "1 Mo": "DGS1MO",
    "2 Mo": "DGS2MO",
    "3 Mo": "DGS3MO",
    "4 Mo": "DGS4MO",
    "6 Mo": "DGS6MO",
    "1 Yr": "DGS1",
    "2 Yr": "DGS2",
    "3 Yr": "DGS3",
    "5 Yr": "DGS5",
    "7 Yr": "DGS7",
    "10 Yr": "DGS10",
    "20 Yr": "DGS20",
    "30 Yr": "DGS30",
}

# FRED series IDs for economic indicators
ECONOMIC_SERIES: dict[str, str] = {
    "FEDFUNDS": "FEDFUNDS",
    "SOFR": "SOFR",
    "CPI": "CPIAUCSL",
    "10Y-2Y Spread": "T10Y2Y",
    "10Y-3M Spread": "T10Y3M",
    "IG Spread": "BAMLC0A0CM",
    "HY Spread": "BAMLH0A0HYM2",
    "Mortgage 30Y": "MORTGAGE30US",
    "5Y Breakeven": "T5YIE",
    "10Y Breakeven": "T10YIE",
    "Unemployment": "UNRATE",
}

DEFAULT_CACHE_TTL: int = 3600  # 1 hour in seconds

# Rating-to-score mapping
RATING_SCORES: dict[str, int] = {
    "AAA": 100,
    "AA+": 95,
    "AA": 90,
    "AA-": 85,
    "A+": 80,
    "A": 75,
    "A-": 70,
    "BBB+": 65,
    "BBB": 60,
    "BBB-": 55,
    "BB+": 50,
    "BB": 45,
    "BB-": 40,
    "B+": 35,
    "B": 30,
    "B-": 25,
    "CCC+": 20,
    "CCC": 15,
    "CCC-": 12,
    "CC": 8,
    "C": 5,
    "D": 0,
}
